name: "Lastest Hashnode Blog Post"

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 * * * *" # Runs every Sunday, on the hour

jobs:
  update_blogs:
    name: "Update With Latest Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "Sachin-chaurasiya/hashnode-blog-action@main"
        with:
          HASHNODE_PUBLICATION_NAME: 'https://sandraashipala.hashnode.dev'
          POST_COUNT: 2 # MAX Visible
          FORMAT: "blog-left"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
