name: "Lastest Hashnode Blog Post"

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 * * * *" # Runs every hour, on the hour

jobs:
  update_blogs:
    name: "Update With Latest Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "sandramsc/hashnode@v1"
        with:
          USERNAME: "sandraashipala" # Hashnode Username
          COUNT: 3 # MAX Visible
          STYLE: "blog-left"
          BLOG_URL: "https://sandraashipala.hashnode.dev/rss.xml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
